### ISSUE TITLE
Visual representation of the pipeline steps

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-ui#48]
Pipeline steps should be represented visually using a DAG, a good example is argo workflow or airflow. 

Example: https://miro.medium.com/max/6400/1*iRBV3v8MI_FGb_24K14HIg.png

**Comment by ankitm123** [comment]
To be shown in the office hours on Aug 2, 2022

**Comment by rajatgupta24** [comment]
Using **D3js** to build d3 tree chart
Current update: 
![image](https://user-images.githubusercontent.com/55191777/185621906-16d87b67-1b27-483c-ade9-586e422dec83.png)

**Comment by rajatgupta24** [comment]
This is a screenshot of DAG in my local environment,

     TODOS
     - Need to test the multiple steps in pr.yaml, also parallel steps.
     - show either chart or logs (because it doesn't update with data).

![image](https://user-images.githubusercontent.com/55191777/185748185-aea7b223-c290-434b-9d6d-9e4955b7ef8e.png)

**Comment by rajatgupta24** [comment]
related to this issue #57

**Comment by ankitm123** [comment]
This can be closed I think, as we are done with this issue.
